Serialization with backrefs
Chia-Network/clvm_rs pull request #192
Opened 2022-06-30 20:02 UTC by richardkiss

2022-07-12 15:34 UTC, arvidn commented
the `Bytes32` type seems to be very similar to the one in `chia_rs`. perhaps some types from there should be moved into `clvm_rs`. Or treehash should be moved to `chia_rs` (and the cache would use some other hashing)

2022-08-20 10:57 UTC, arvidn commented
@richardkiss Please add a description to this PR. Thins that aren't obvious to me are:

1. what are all the new dependencies for? Are they all transitive dependencies from bumping the crypto package version?
2. There appears to be an implementation of this in CLVM also, why?
3. what's "swbr" short for?

2022-08-20 12:11 UTC, arvidn requested changes
I'm interested in benchmarks of code.
1. how much space savings does it give us? (say, on average in the last 100000 blocks).
2. What's the trade-off between saving bytes and paying higher CLVM cost for decompression?
3. how much more expensive is it to decompress? (I imagine that's the most relevant metric)
4. What's the worst case scenario? Are there any sensitive parts that could be a DoS vector? having some worst-case benchmarks would be great. The worst case memory usage would also be interesting. I think there's some potential for reducing the memory footprint (and the worst case is already pretty high without compression).

There should also be coverage of the compression end of things. It's important farmers don't fail to produce a block.

Generally, there are a lot of missing unit tests. I would also expect somewhat extensive round-trip tests, to ensure all edge cases in the compression can be decompressed.

I think both the rust and clvm implementation of decompression should have a fuzzer driver. We have all the infrastructure in place for that, so it shouldn't be a bit deal to add.
Maybe even the serializer could be fuzzed, it's a bit tricky though, since the tree structure would need to be built from a noise input.

Lastly, the serialization format needs to be documented.

2022-08-20 12:11 UTC, arvidn commented on src/read_cache_lookup.rs
> +fn reversed_path_to_vec_u8(path: &[u8]) -> Vec<u8> {
could you add a comment describing what this function does?

2022-08-20 12:11 UTC, arvidn commented on src/read_cache_lookup.rs
> +impl ReadCacheLookup {
this class should have unit tests

2022-08-20 16:16 UTC, arvidn commented
It seems likely that we would get more savings by applying this compression at the db layer and leave the farmed blocks as they are.

* We wouldn't have to wrap the generator in the decompressor program (which is a lot of repetitive code)
* We could decompress it in rust, which would be faster and use less memory

2022-08-23 00:58 UTC, richardkiss commented
> @richardkiss Please add a description to this PR. Thins that aren't obvious to me are:
> 
> 1. what are all the new dependencies for? Are they all transitive dependencies from bumping the crypto package version?
> 2. There appears to be an implementation of this in CLVM also, why?
> 3. what's "swbr" short for?

1. The new dependencies are likely all for the new command-line tool `swbr` (argument parsing, etc.)
2. I wrote this in python first as a proof-of-concept, then ported it to rust. The speed-up was surprisingly marginal, and in fact, `debug` rust is *slower* than python, which makes me think maybe there's some issue in the rust. With `--release`, it's several times faster though – but not 10x, which you might expect. I can't find a problem though, and the outputs are byte-for-byte identical in my tests.
3. `streaming with back-references`

2022-08-23 01:02 UTC, richardkiss commented
> It seems likely that we would get more savings by applying this compression at the db layer and leave the farmed blocks as they are.
> 
> * We wouldn't have to wrap the generator in the decompressor program (which is a lot of repetitive code)
> * We could decompress it in rust, which would be faster and use less memory
> 
> EDIT: I suppose it depends on the cost of decompresison in CLVM. it looks like the format was chosen to make it cheap to decompress.

This is intended to be used as a generator compressor only, by farmers, on a going-forward basis (since we commit the tree hash of the generator, not the generator's output), where we are restricted to writing a decompressor in clvm. Each generator must include the decompressor program. However, it's not actually very large, and it still seems to be quite a large win.

For the DB, probably `zstd` is what you want (although you might make it optional, since some file systems like zfs support `zstd` compression at the file system layer). I expect `zstd` will be able to further compress even generators with back-references.

2022-12-13 09:50 UTC, trepca commented
@richardkiss is this still being worked on?

2022-12-22 03:11 UTC, richardkiss commented
Duplicate with https://github.com/Chia-Network/clvm_rs/pull/222

2022-12-22 03:11 UTC, closed without merging